version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python:3.9
    volumes:
      - '.:/app'
      - 'pipenv:/root/.local/share'
    tty: true
    working_dir: '/app'
volumes:
  pipenv:
    driver: local
